import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { IMainMenu } from '../../types/interfaces/i-main-menu';
import { IMainMenuService } from '../i-main-menu.service';

@Injectable()
export class MainMenuService implements IMainMenuService {
    constructor(private http: HttpClient) { }

    public getMenu(): Observable<IMainMenu[]> {
        return of(this.getMainMenu());
    }

    private getMainMenu(): IMainMenu[] {
        const menu: IMainMenu[] = [
            {
                id: 1,
                name: 'Справочники',
                url: '',
                image: '',
                level: 1,
                children: [
                    {
                        id: 11,
                        name: 'Реестры',
                        url: '',
                        image: './assets/maintheme/images/icons/reest.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 111,
                                name: 'Банки',
                                url: '/catalogs/banks',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 112,
                                name: 'Валюты',
                                url: '/catalogs/currency',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 113,
                                name: 'Единицы измерения',
                                url: '/catalogs/unit',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 114,
                                name: 'Должности',
                                url: '/catalogs/posts',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 115,
                                name: 'Формы собственности',
                                url: '/catalogs/formown',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 116,
                                name: 'Действующие вещеста',
                                url: '/catalogs/substance',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 117,
                                name: 'Симптомы',
                                url: '/catalogs/symptom',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 118,
                                name: 'Формы выпуска',
                                url: '/catalogs/formfactory',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                            {
                                id: 119,
                                name: 'Налоговые ставки',
                                url: '/catalogs/taxrate',
                                image: '',
                                level: 3,
                                parentId: 11,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: 12,
                        name: 'Адреса',
                        url: '/catalogs/location',
                        image: './assets/maintheme/images/icons/map.svg',
                        level: 2,
                        parentId: 1,
                        children: [],
                    },
                    {
                        id: 13,
                        name: 'Физические лица',
                        url: '',
                        image: './assets/maintheme/images/icons/fizlico.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 131,
                                name: 'Физические лица',
                                url: '/catalogs/employee',
                                image: '',
                                level: 3,
                                parentId: 12,
                                children: [],
                            },
                            {
                                id: 132,
                                name: 'Сотрудники фирмы',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 12,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: 14,
                        name: 'Контрагенты',
                        url: '',
                        image: './assets/maintheme/images/icons/contragent.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 141,
                                name: 'Фирмы учета',
                                url: '/catalogs/firm',
                                image: '',
                                level: 3,
                                parentId: 14,
                                children: [],
                            },
                            {
                                id: 142,
                                name: 'Группы контрагентов',
                                url: '/catalogs/firmgroup',
                                image: '',
                                level: 3,
                                parentId: 14,
                                children: [],
                            },
                            {
                                id: 143,
                                name: 'Группы контрагента',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 14,
                                children: [],
                            },
                            {
                                id: 144,
                                name: 'Настройки фирмы',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 14,
                                children: [],
                            },
                            {
                                id: 145,
                                name: 'Банковские счета фирмы',
                                url: '/catalogs/firmaccount',
                                image: '',
                                level: 3,
                                parentId: 14,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: 15,
                        name: 'Товары',
                        url: '',
                        image: './assets/maintheme/images/icons/test.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 151,
                                name: 'Товар',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 152,
                                name: 'Перевод к другим единицам',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 153,
                                name: 'Штрих коды',
                                url: '/catalogs/productbar',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 154,
                                name: 'Действующие вещества',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 155,
                                name: 'Симптомы',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 156,
                                name: 'Менеджер товара',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 157,
                                name: 'Группа товара',
                                url: '/catalogs/productgroup',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 158,
                                name: 'Бренд товара',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 159,
                                name: 'Вид товара',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 1510,
                                name: 'Категория ЛС по классификации',
                                url: '/catalogs/productcategory',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 1511,
                                name: 'Государственное регулирование цен',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            },
                            {
                                id: 1512,
                                name: 'Ценовая группа товара',
                                url: '/catalogs/groupprice',
                                image: '',
                                level: 3,
                                parentId: 15,
                                children: [],
                            }
                        ],
                    },
                    {
                        id: 16,
                        name: 'Подразделения',
                        url: '',
                        image: './assets/maintheme/images/icons/units.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 161,
                                name: 'Подразделения фирмы',
                                url: '/catalogs/structure',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                            {
                                id: 162,
                                name: 'Оборудование',
                                url: '/catalogs/device',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                            {
                                id: 163,
                                name: 'Модели оборудования',
                                url: '/catalogs/devicemodel',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                            {
                                id: 164,
                                name: 'Кассы',
                                url: '/catalogs/cashbox',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                            {
                                id: 165,
                                name: 'Группа разрешений кассы',
                                url: '/catalogs/cashboxpermit',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                            {
                                id: 166,
                                name: 'Разрешения по операциям в группе',
                                url: '/catalogs/cashboxpermitaction',
                                image: '',
                                level: 3,
                                parentId: 16,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: 17,
                        name: 'Склады',
                        url: '',
                        image: './assets/maintheme/images/icons/warehouse.svg',
                        level: 2,
                        parentId: 1,
                        children: [
                            {
                                id: 171,
                                name: 'Склад',
                                url: '/catalogs/store',
                                image: '',
                                level: 3,
                                parentId: 17,
                                children: [],
                            },
                            {
                                id: 172,
                                name: 'Структура склада',
                                url: '/catalogs/storeframe',
                                image: '',
                                level: 3,
                                parentId: 17,
                                children: [],
                            },
                            {
                                id: 173,
                                name: 'Условия хранения',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 17,
                                children: [],
                            },
                        ],
                    },
                ],
            },
            {
                id: 2,
                name: 'Товары',
                url: 'google.com',
                image: '',
                level: 1,
                children: [
                    {
                        id: 21,
                        name: 'Прием товара',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/priem.svg',
                        level: 2,
                        parentId: 2,
                        children: [
                            {
                                id: 221,
                                name: 'Приходные накладные',
                                url: '/banks',
                                image: '',
                                level: 3,
                                parentId: 7,
                                children: [],
                            },
                            {
                                id: 222,
                                name: 'Сортировка',
                                url: '',
                                image: '',
                                level: 3,
                                parentId: 7,
                                children: [],
                            },
                        ],
                    },
                    {
                        id: 22,
                        name: 'Претензии и возвраты',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/pretenzii.svg',
                        level: 2,
                        parentId: 2,
                        children: [],
                    },
                    {
                        id: 23,
                        name: 'Возвраты от покупателя',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/vozvrat.svg',
                        level: 2,
                        parentId: 2,
                        children: [],
                    },
                    {
                        id: 24,
                        name: 'Инвентаризация',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/inventar.svg',
                        level: 2,
                        parentId: 2,
                        children: [],
                    },
                    {
                        id: 25,
                        name: 'Утилизация',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/utilization.svg',
                        level: 2,
                        parentId: 2,
                        children: [],
                    },
                ],
            },
            {
                id: 4,
                name: 'Документы',
                url: 'google.com',
                image: '',
                level: 1,
                children: [
                    {
                        id: 41,
                        name: 'Накладные',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/nakladnie.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 42,
                        name: 'Чеки',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/chek.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 43,
                        name: 'Реестр накладных',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/reestr.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 44,
                        name: 'Реестр товарных документов',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/reestrtovara.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 45,
                        name: 'Акт пересортицы',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/peresortica.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 46,
                        name: 'Переоценка',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/pereocenka.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                    {
                        id: 47,
                        name: 'Списание',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/spisanie.svg',
                        level: 2,
                        parentId: 4,
                        children: [],
                    },
                ],
            },

            {
                id: 3,
                name: 'Пополнение остатков',
                url: 'google.com',
                image: '',
                level: 1,
                children: [
                    {
                        id: 31,
                        name: 'ЦБД остатков',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/cbd.svg',
                        level: 2,
                        parentId: 3,
                        children: [],
                    },
                    {
                        id: 32,
                        name: 'Под заказ',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/podzakaz.svg',
                        level: 2,
                        parentId: 3,
                        children: [],
                    },
                    {
                        id: 33,
                        name: 'Заказ у поставщика',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/postavka.svg',
                        level: 2,
                        parentId: 3,
                        children: [],
                    },
                    {
                        id: 34,
                        name: 'Заказы',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/orders.svg',
                        level: 2,
                        parentId: 3,
                        children: [],
                    },
                ],
            },
            {
                id: 5,
                name: 'Аналитика',
                url: 'google.com',
                image: '',
                level: 1,
                children: [
                    {
                        id: 51,
                        name: 'Отчеты',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/otchet.svg',
                        level: 2,
                        parentId: 5,
                        children: [],
                    },
                    {
                        id: 52,
                        name: 'Персонал',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/personal.svg',
                        level: 2,
                        parentId: 5,
                        children: [],
                    },
                ],
            },
            {
                id: 6,
                name: 'Настройки',
                url: 'google.com',
                image: '',
                level: 1,
                children: [
                    {
                        id: 61,
                        name: 'Установки',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/ustanovka.svg',
                        level: 2,
                        parentId: 6,
                        children: [],
                    },
                    {
                        id: 62,
                        name: 'Параметры печати',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/print.svg',
                        level: 2,
                        parentId: 6,
                        children: [],
                    },
                    {
                        id: 63,
                        name: 'Версии',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/branch.svg',
                        level: 2,
                        parentId: 6,
                        children: [],
                    },
                    {
                        id: 64,
                        name: 'Справка',
                        url: 'google.com',
                        image: './assets/maintheme/images/icons/faq.svg',
                        level: 2,
                        parentId: 6,
                        children: [],
                    },
                ],
            },
        ];

        return menu;
    }
}
